# https://goreleaser.com/ci/actions/
name: Build test

on:
  pull_request:
  push:

permissions:
  contents: read

jobs:
  build_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: latest
          # skips announce and artifact uploads
          # https://goreleaser.com/cmd/goreleaser_release/
          args: release --rm-dist --skip-announce --skip-publish
